[package]
name = "cargo8885"
version = "0.1.0"
authors = ["Aidan Cully <github@aidan.users.panix.com>"]
edition = "2018"

[lib]
name = "cargo8885"
crate-type = ["rlib"]

[workspace]
members = ["src/member"]
